lock-version = "1.0"
created-by = "uv"
requires-python = ">=3.14.2"

[[packages]]
name = "workers-runtime-sdk"
version = "1.8.6"
wheels = [{ url = "https://files.pythonhosted.org/packages/a1/18/a23cad74fe1f2a6d53fa41ca7df17b0d8d81c110f9ccfc5d1d4ce7894dca/workers_runtime_sdk-1.8.6-py3-none-any.whl", upload-time = 2026-09-18T04:40:22Z, size = 36520, hashes = { sha256 = "a230dd2fa528ffdeada98bdfd5a336f1753ae2844ae920f965233153471dbc29" } }]
